image:
  repository: tccr.io/truecharts/immich-server
  tag: v1.72.2@sha256:b77f923a3a54e9b8c29eb2750cc4bd3d1e8b7a357b42a42893014acdbe4fbb1c
  pullPolicy: IfNotPresent
mlImage:
  repository: tccr.io/truecharts/immich-ml
  tag: v1.72.1@sha256:5e2cc585b8f15239d10b8e04c87ad7ea79ca4ef4e6f6a84f679afbb429026dda
  pullPolicy: IfNotPresent
webImage:
  repository: tccr.io/truecharts/immich-web
  tag: v1.72.2@sha256:f54619d64ad940a65aa70dfd187eb7921d73788b0984e002bba8d5b32031792c
  pullPolicy: IfNotPresent
proxyImage:
  repository: tccr.io/truecharts/immich-proxy
  tag: v1.72.1@sha256:444fb41018a6f834b096898a8aabfacb4e41ae06587c2048a6db1c79c4a56a92
  pullPolicy: IfNotPresent
typesenseImage:
  repository: tccr.io/truecharts/immich-typesense
  tag: v0.24.1@sha256:1e46a13a98670c98b483e0cbbf66f05aa418146e7edf447446ae72f3bb8477ac
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

immich:
  enable_ml: true
  enable_typesense: true
  public_login_page_message: Immich
  disable_reverse_geocoding: false
  reverse_geocoding_precision: 3
  log_level: log

service:
  main:
    # Main service targets the proxy
    targetSelector: proxy
    ports:
      main:
        port: 10323
        protocol: http
        targetSelector: proxy
        targetPort: 8080
  server:
    enabled: true
    type: ClusterIP
    # Server is the main container
    targetSelector: main
    ports:
      server:
        enabled: true
        primary: true
        port: 10001
        protocol: http
        targetSelector: main
  web:
    enabled: true
    type: ClusterIP
    targetSelector: web
    ports:
      web:
        enabled: true
        primary: true
        port: 10000
        protocol: http
        targetSelector: web
  microservices:
    enabled: true
    type: ClusterIP
    targetSelector: microservices
    ports:
      microservices:
        enabled: true
        primary: true
        port: 10004
        protocol: http
        targetSelector: microservices
  machinelearning:
    enabled: true
    type: ClusterIP
    targetSelector: machinelearning
    ports:
      machinelearning:
        enabled: true
        primary: true
        port: 10003
        protocol: http
        targetSelector: machinelearning
  typesense:
    enabled: true
    type: ClusterIP
    targetSelector: typesense
    ports:
      typesense:
        enabled: true
        primary: true
        port: 10002
        protocol: http
        targetSelector: typesense

persistence:
  mlcache:
    enabled: true
    type: emptyDir
    targetSelector:
      machinelearning:
        machinelearning:
          mountPath: /mlcache
  microcache:
    enabled: true
    type: emptyDir
    targetSelector:
      microservices:
        microservices:
          mountPath: /microcache
  typesense:
    enabled: true
    type: emptyDir
    targetSelector:
      typesense:
        typesense:
          mountPath: /typesensedata
  library:
    enabled: true
    mountPath: /usr/src/app/upload/library
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  uploads:
    enabled: true
    mountPath: /usr/src/app/upload/upload
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  thumbs:
    enabled: true
    mountPath: /usr/src/app/upload/thumbs
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  profile:
    enabled: true
    mountPath: /usr/src/app/upload/profile
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  video:
    enabled: true
    mountPath: /usr/src/app/upload/encoded-video
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}

cnpg:
  main:
    enabled: true
    user: immich
    database: immich

redis:
  enabled: true
  redisUsername: default

portal:
  open:
    enabled: true
